# Generated by Django 6.1.1 on 2026-10-05 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collections", "0003_collection_secrets"),
        ("entries", "0005_retire_price_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_wish_list",
            field=models.BooleanField(default=False, verbose_name="wish list"),
        ),
        migrations.CreateModel(
            name="GotIt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "got_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="got at"),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="got_its",
                        to="collections.collection",
                        verbose_name="collection",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="got_its",
                        to="entries.entry",
                        verbose_name="entry",
                    ),
                ),
                (
                    "got_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="got by",
                    ),
                ),
            ],
            options={
                "verbose_name": "got it",
                "verbose_name_plural": "got its",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("collection", "entry"), name="one_got_it_per_list_entry"
                    )
                ],
            },
        ),
    ]
