# Generated by Django 6.1.1 on 2026-10-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0005_retire_price_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("name",),
                "verbose_name": "label",
                "verbose_name_plural": "labels",
            },
        ),
        migrations.AlterField(
            model_name="entry",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="entries",
                to="entries.tag",
                verbose_name="labels",
            ),
        ),
    ]
